name:                polysemy-sdl
version:             0.1.0.0
github:              "ab9rf/polysemy-sdl"
license:             BSD3
author:              "Kelly Kinkade"
maintainer:          "kmartin@pyrzqxgl.org"
copyright:           "unspecified"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            unspecified

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ab9rf/polysemy-sdl#readme>

dependencies:
- base >= 4.7 && < 5
- sdl2 >= 2.2.0
- polysemy >= 1.0.0
- text

ghc-options: -O2 -flate-specialise -fspecialise-aggressively 
default-extensions:
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies

library:
  source-dirs: src
  
tests:
  polysemy-sdl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - polysemy-sdl

